import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    safelist: [
        // Основные цвета с opacity
        'bg-accent-green/5', 'bg-accent-green/10', 'bg-accent-green/20', 'bg-accent-green/30', 'bg-accent-green/40', 'bg-accent-green/50',
        'bg-accent-blue/5', 'bg-accent-blue/10', 'bg-accent-blue/20', 'bg-accent-blue/30', 'bg-accent-blue/40', 'bg-accent-blue/50',
        'bg-accent-yellow/5', 'bg-accent-yellow/10', 'bg-accent-yellow/20', 'bg-accent-yellow/30', 'bg-accent-yellow/40', 'bg-accent-yellow/50',
        'bg-accent-red/5', 'bg-accent-red/10', 'bg-accent-red/20', 'bg-accent-red/30', 'bg-accent-red/40', 'bg-accent-red/50',
        'bg-accent-purple/5', 'bg-accent-purple/10', 'bg-accent-purple/20', 'bg-accent-purple/30', 'bg-accent-purple/40', 'bg-accent-purple/50',
        'bg-accent-pink/5', 'bg-accent-pink/10', 'bg-accent-pink/20', 'bg-accent-pink/30', 'bg-accent-pink/40', 'bg-accent-pink/50',
        'bg-accent-cyan/5', 'bg-accent-cyan/10', 'bg-accent-cyan/20', 'bg-accent-cyan/30', 'bg-accent-cyan/40', 'bg-accent-cyan/50',
        'bg-accent-emerald/5', 'bg-accent-emerald/10', 'bg-accent-emerald/20', 'bg-accent-emerald/30', 'bg-accent-emerald/40', 'bg-accent-emerald/50',
        'bg-accent-indigo/5', 'bg-accent-indigo/10', 'bg-accent-indigo/20', 'bg-accent-indigo/30', 'bg-accent-indigo/40', 'bg-accent-indigo/50',
        'bg-accent-violet/5', 'bg-accent-violet/10', 'bg-accent-violet/20', 'bg-accent-violet/30', 'bg-accent-violet/40', 'bg-accent-violet/50',
        'bg-accent-fuchsia/5', 'bg-accent-fuchsia/10', 'bg-accent-fuchsia/20', 'bg-accent-fuchsia/30', 'bg-accent-fuchsia/40', 'bg-accent-fuchsia/50',
        'bg-accent-rose/5', 'bg-accent-rose/10', 'bg-accent-rose/20', 'bg-accent-rose/30', 'bg-accent-rose/40', 'bg-accent-rose/50',
        'bg-accent-orange/5', 'bg-accent-orange/10', 'bg-accent-orange/20', 'bg-accent-orange/30', 'bg-accent-orange/40', 'bg-accent-orange/50',
        'bg-accent-lime/5', 'bg-accent-lime/10', 'bg-accent-lime/20', 'bg-accent-lime/30', 'bg-accent-lime/40', 'bg-accent-lime/50',
        'bg-accent-teal/5', 'bg-accent-teal/10', 'bg-accent-teal/20', 'bg-accent-teal/30', 'bg-accent-teal/40', 'bg-accent-teal/50',
        'bg-accent-sky/5', 'bg-accent-sky/10', 'bg-accent-sky/20', 'bg-accent-sky/30', 'bg-accent-sky/40', 'bg-accent-sky/50',
        'bg-accent-slate/5', 'bg-accent-slate/10', 'bg-accent-slate/20', 'bg-accent-slate/30', 'bg-accent-slate/40', 'bg-accent-slate/50',
        'bg-accent-zinc/5', 'bg-accent-zinc/10', 'bg-accent-zinc/20', 'bg-accent-zinc/30', 'bg-accent-zinc/40', 'bg-accent-zinc/50',
        'bg-accent-neutral/5', 'bg-accent-neutral/10', 'bg-accent-neutral/20', 'bg-accent-neutral/30', 'bg-accent-neutral/40', 'bg-accent-neutral/50',
        'bg-accent-stone/5', 'bg-accent-stone/10', 'bg-accent-stone/20', 'bg-accent-stone/30', 'bg-accent-stone/40', 'bg-accent-stone/50',
        'bg-accent-gray/5', 'bg-accent-gray/10', 'bg-accent-gray/20', 'bg-accent-gray/30', 'bg-accent-gray/40', 'bg-accent-gray/50',
        
        // Границы с opacity
        'border-accent-green/30', 'border-accent-green/50',
        'border-accent-blue/30', 'border-accent-blue/50',
        'border-accent-yellow/30', 'border-accent-yellow/50',
        'border-accent-red/30', 'border-accent-red/50',
        'border-accent-purple/30', 'border-accent-purple/50',
        'border-accent-pink/30', 'border-accent-pink/50',
        'border-accent-cyan/30', 'border-accent-cyan/50',
        'border-accent-emerald/30', 'border-accent-emerald/50',
        'border-accent-indigo/30', 'border-accent-indigo/50',
        'border-accent-violet/30', 'border-accent-violet/50',
        'border-accent-fuchsia/30', 'border-accent-fuchsia/50',
        'border-accent-rose/30', 'border-accent-rose/50',
        'border-accent-orange/30', 'border-accent-orange/50',
        'border-accent-lime/30', 'border-accent-lime/50',
        'border-accent-teal/30', 'border-accent-teal/50',
        'border-accent-sky/30', 'border-accent-sky/50',
        'border-accent-slate/30', 'border-accent-slate/50',
        'border-accent-zinc/30', 'border-accent-zinc/50',
        'border-accent-neutral/30', 'border-accent-neutral/50',
        'border-accent-stone/30', 'border-accent-stone/50',
        'border-accent-gray/30', 'border-accent-gray/50',
        
        // Hover эффекты
        'hover:bg-accent-green/10', 'hover:bg-accent-green/20', 'hover:bg-accent-green/30',
        'hover:bg-accent-blue/10', 'hover:bg-accent-blue/20', 'hover:bg-accent-blue/30',
        'hover:bg-accent-yellow/10', 'hover:bg-accent-yellow/20', 'hover:bg-accent-yellow/30',
        'hover:bg-accent-red/10', 'hover:bg-accent-red/20', 'hover:bg-accent-red/30',
        'hover:bg-accent-purple/10', 'hover:bg-accent-purple/20', 'hover:bg-accent-purple/30',
        'hover:bg-accent-pink/10', 'hover:bg-accent-pink/20', 'hover:bg-accent-pink/30',
        'hover:bg-accent-cyan/10', 'hover:bg-accent-cyan/20', 'hover:bg-accent-cyan/30',
        'hover:bg-accent-emerald/10', 'hover:bg-accent-emerald/20', 'hover:bg-accent-emerald/30',
        'hover:bg-accent-indigo/10', 'hover:bg-accent-indigo/20', 'hover:bg-accent-indigo/30',
        'hover:bg-accent-violet/10', 'hover:bg-accent-violet/20', 'hover:bg-accent-violet/30',
        'hover:bg-accent-fuchsia/10', 'hover:bg-accent-fuchsia/20', 'hover:bg-accent-fuchsia/30',
        'hover:bg-accent-rose/10', 'hover:bg-accent-rose/20', 'hover:bg-accent-rose/30',
        'hover:bg-accent-orange/10', 'hover:bg-accent-orange/20', 'hover:bg-accent-orange/30',
        'hover:bg-accent-lime/10', 'hover:bg-accent-lime/20', 'hover:bg-accent-lime/30',
        'hover:bg-accent-teal/10', 'hover:bg-accent-teal/20', 'hover:bg-accent-teal/30',
        'hover:bg-accent-sky/10', 'hover:bg-accent-sky/20', 'hover:bg-accent-sky/30',
        'hover:bg-accent-slate/10', 'hover:bg-accent-slate/20', 'hover:bg-accent-slate/30',
        'hover:bg-accent-zinc/10', 'hover:bg-accent-zinc/20', 'hover:bg-accent-zinc/30',
        'hover:bg-accent-neutral/10', 'hover:bg-accent-neutral/20', 'hover:bg-accent-neutral/30',
        'hover:bg-accent-stone/10', 'hover:bg-accent-stone/20', 'hover:bg-accent-stone/30',
        'hover:bg-accent-gray/10', 'hover:bg-accent-gray/20', 'hover:bg-accent-gray/30',
        
        // Hover границы
        'hover:border-accent-green/30', 'hover:border-accent-blue/30', 'hover:border-accent-yellow/30', 'hover:border-accent-red/30',
        'hover:border-accent-purple/30', 'hover:border-accent-pink/30', 'hover:border-accent-cyan/30', 'hover:border-accent-emerald/30',
        'hover:border-accent-indigo/30', 'hover:border-accent-violet/30', 'hover:border-accent-fuchsia/30', 'hover:border-accent-rose/30',
        'hover:border-accent-orange/30', 'hover:border-accent-lime/30', 'hover:border-accent-teal/30', 'hover:border-accent-sky/30',
        'hover:border-accent-slate/30', 'hover:border-accent-zinc/30', 'hover:border-accent-neutral/30', 'hover:border-accent-stone/30',
        'hover:border-accent-gray/30',
        
        // Тени
        'shadow-glow-blue', 'shadow-glow-green', 'shadow-glow-purple', 'shadow-glow-yellow', 'shadow-glow-red',
        'shadow-glow-cyan', 'shadow-glow-emerald', 'shadow-glow-indigo', 'shadow-glow-violet', 'shadow-glow-fuchsia',
        'shadow-glow-rose', 'shadow-glow-orange', 'shadow-glow-lime', 'shadow-glow-teal', 'shadow-glow-sky',
        'shadow-glow-slate', 'shadow-glow-zinc', 'shadow-glow-neutral', 'shadow-glow-stone', 'shadow-glow-gray',
        
        // Типографика
        'text-heading-1', 'text-heading-2', 'text-heading-3', 'text-heading-4',
        'text-body-large', 'text-body', 'text-body-small', 'text-caption',
        
        // Анимации
        'animate-fade-in', 'animate-slide-up', 'animate-slide-down', 'animate-scale-in',
        'animate-float', 'animate-glow', 'animate-pulse', 'animate-bounce', 'animate-spin',
        'animate-ping', 'animate-wiggle',
        
        // Backdrop blur
        'backdrop-blur-sm', 'backdrop-blur', 'backdrop-blur-md', 'backdrop-blur-lg',
        'backdrop-blur-xl', 'backdrop-blur-2xl', 'backdrop-blur-3xl',
        
        // Скроллбары
        'scrollbar-thin', 'scrollbar-thumb-border-color', 'scrollbar-track-transparent',
        
        // Утилиты
        'line-clamp-2', 'line-clamp-3', 'line-clamp-4',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                'primary-bg': 'var(--primary-bg)',
                'secondary-bg': 'var(--secondary-bg)',
                'card-bg': 'var(--card-bg)',
                'border-color': 'var(--border-color)',
                'text-primary': 'var(--text-primary)',
                'text-secondary': 'var(--text-secondary)',
                'text-muted': 'var(--text-muted)',
                'accent-green': 'var(--accent-green)',
                'accent-blue': 'var(--accent-blue)',
                'accent-yellow': 'var(--accent-yellow)',
                'accent-red': 'var(--accent-red)',
                'accent-purple': 'var(--accent-purple)',
                'accent-pink': 'var(--accent-pink)',
                'accent-cyan': 'var(--accent-cyan)',
                'accent-emerald': 'var(--accent-emerald)',
                'accent-indigo': 'var(--accent-indigo)',
                'accent-violet': 'var(--accent-violet)',
                'accent-fuchsia': 'var(--accent-fuchsia)',
                'accent-rose': 'var(--accent-rose)',
                'accent-orange': 'var(--accent-orange)',
                'accent-lime': 'var(--accent-lime)',
                'accent-teal': 'var(--accent-teal)',
                'accent-sky': 'var(--accent-sky)',
                'accent-slate': 'var(--accent-slate)',
                'accent-zinc': 'var(--accent-zinc)',
                'accent-neutral': 'var(--accent-neutral)',
                'accent-stone': 'var(--accent-stone)',
                'accent-gray': 'var(--accent-gray)',
                'accent-red-soft': 'var(--accent-red-soft)',
                'accent-yellow-soft': 'var(--accent-yellow-soft)',
                'accent-green-soft': 'var(--accent-green-soft)',
                'accent-blue-soft': 'var(--accent-blue-soft)',
                'accent-purple-soft': 'var(--accent-purple-soft)',
                'accent-pink-soft': 'var(--accent-pink-soft)',
                'accent-cyan-soft': 'var(--accent-cyan-soft)',
                'accent-emerald-soft': 'var(--accent-emerald-soft)',
                'accent-indigo-soft': 'var(--accent-indigo-soft)',
                'accent-violet-soft': 'var(--accent-violet-soft)',
                'accent-fuchsia-soft': 'var(--accent-fuchsia-soft)',
                'accent-rose-soft': 'var(--accent-rose-soft)',
                'accent-orange-soft': 'var(--accent-orange-soft)',
                'accent-lime-soft': 'var(--accent-lime-soft)',
                'accent-teal-soft': 'var(--accent-teal-soft)',
                'accent-sky-soft': 'var(--accent-sky-soft)',
                'accent-slate-soft': 'var(--accent-slate-soft)',
                'accent-zinc-soft': 'var(--accent-zinc-soft)',
                'accent-neutral-soft': 'var(--accent-neutral-soft)',
                'accent-stone-soft': 'var(--accent-stone-soft)',
                'accent-gray-soft': 'var(--accent-gray-soft)',
            },
            borderRadius: {
                'sm': 'var(--radius-sm)',
                'DEFAULT': 'var(--radius)',
                'md': 'var(--radius-md)',
                'lg': 'var(--radius-lg)',
                'xl': 'var(--radius-xl)',
                '2xl': 'var(--radius-2xl)',
                '3xl': 'var(--radius-3xl)',
                'full': 'var(--radius-full)',
            },
            boxShadow: {
                'sm': 'var(--shadow-sm)',
                'DEFAULT': 'var(--shadow)',
                'md': 'var(--shadow-md)',
                'lg': 'var(--shadow-lg)',
                'xl': 'var(--shadow-xl)',
                '2xl': 'var(--shadow-2xl)',
                'inner': 'var(--shadow-inner)',
                'glow-blue': 'var(--shadow-glow-blue)',
                'glow-green': 'var(--shadow-glow-green)',
                'glow-purple': 'var(--shadow-glow-purple)',
                'glow-yellow': 'var(--shadow-glow-yellow)',
                'glow-red': 'var(--shadow-glow-red)',
                'glow-cyan': 'var(--shadow-glow-cyan)',
                'glow-emerald': 'var(--shadow-glow-emerald)',
                'glow-indigo': 'var(--shadow-glow-indigo)',
                'glow-violet': 'var(--shadow-glow-violet)',
                'glow-fuchsia': 'var(--shadow-glow-fuchsia)',
                'glow-rose': 'var(--shadow-glow-rose)',
                'glow-orange': 'var(--shadow-glow-orange)',
                'glow-lime': 'var(--shadow-glow-lime)',
                'glow-teal': 'var(--shadow-glow-teal)',
                'glow-sky': 'var(--shadow-glow-sky)',
                'glow-slate': 'var(--shadow-glow-slate)',
                'glow-zinc': 'var(--shadow-glow-zinc)',
                'glow-neutral': 'var(--shadow-glow-neutral)',
                'glow-stone': 'var(--shadow-glow-stone)',
                'glow-gray': 'var(--shadow-glow-gray)',
            },
            animation: {
                'fade-in': 'fadeIn 0.6s ease-out',
                'slide-up': 'slideUp 0.8s ease-out',
                'slide-down': 'slideDown 0.8s ease-out',
                'scale-in': 'scaleIn 0.6s ease-out',
                'blob': 'blob 7s infinite',
                'float': 'float 3s ease-in-out infinite',
                'glow': 'glow 2s ease-in-out infinite alternate',
                'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'bounce': 'bounce 1s infinite',
                'spin': 'spin 1s linear infinite',
                'ping': 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
                'wiggle': 'wiggle 1s ease-in-out infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0', transform: 'translateY(10px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                slideUp: {
                    '0%': { opacity: '0', transform: 'translateY(20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                slideDown: {
                    '0%': { opacity: '0', transform: 'translateY(-20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                scaleIn: {
                    '0%': { opacity: '0', transform: 'scale(0.9)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                blob: {
                    '0%': { transform: 'translate(0px, 0px) scale(1)' },
                    '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
                    '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
                    '100%': { transform: 'translate(0px, 0px) scale(1)' },
                },
                float: {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-10px)' },
                },
                glow: {
                    '0%': { boxShadow: '0 0 5px rgba(255, 255, 255, 0.1)' },
                    '100%': { boxShadow: '0 0 20px rgba(255, 255, 255, 0.3)' },
                },
                pulse: {
                    '0%, 100%': { opacity: '1' },
                    '50%': { opacity: '0.5' },
                },
                bounce: {
                    '0%, 100%': { transform: 'translateY(-25%)', animationTimingFunction: 'cubic-bezier(0.8, 0, 1, 1)' },
                    '50%': { transform: 'none', animationTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)' },
                },
                spin: {
                    'from': { transform: 'rotate(0deg)' },
                    'to': { transform: 'rotate(360deg)' },
                },
                ping: {
                    '75%, 100%': { transform: 'scale(2)', opacity: '0' },
                },
                wiggle: {
                    '0%, 100%': { transform: 'rotate(-3deg)' },
                    '50%': { transform: 'rotate(3deg)' },
                },
            },
            transitionDelay: {
                '100': '100ms',
                '200': '200ms',
                '300': '300ms',
                '400': '400ms',
                '500': '500ms',
                '600': '600ms',
                '700': '700ms',
                '800': '800ms',
                '900': '900ms',
                '1000': '1000ms',
                '1100': '1100ms',
                '1200': '1200ms',
            },
            backdropBlur: {
                'xs': '2px',
            },
            fontSize: {
                'heading-1': ['2.25rem', { lineHeight: '2.5rem', fontWeight: '700', letterSpacing: '-0.025em' }],
                'heading-2': ['1.875rem', { lineHeight: '2.25rem', fontWeight: '600', letterSpacing: '-0.025em' }],
                'heading-3': ['1.5rem', { lineHeight: '2rem', fontWeight: '600', letterSpacing: '-0.025em' }],
                'heading-4': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '600', letterSpacing: '-0.025em' }],
                'body-large': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '400' }],
                'body': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
                'body-small': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
                'caption': ['0.75rem', { lineHeight: '1rem', fontWeight: '400' }],
            },
        },
    },

    plugins: [forms],
};
